### ISSUE TITLE
Encourage people to add to the underscore label registry

### ISSUE THREAD

**Issue by enygren** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#104]
As discussed at the mic, we should encourage people add labels to the dns node names registry:

https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#underscored-globally-scoped-dns-node-names

**Comment by paulwouters** [comment]
On Nov 7, 2023, at 17:34, Erik Nygren ***@***.***> wrote:
> 
> As discussed at the mic, we should encourage people add labels to the dns node names registry:
> 
> https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#underscored-globally-scoped-dns-node-names
> 

So I am one of the Delegated Expert on that registry. So I have some experience with its entries.

There is a use case for people registering names in that registry to avoid clashing. Eg if Company X would have something database like at _db.example.com it would be good not to conflict with Company Y that uses the same record for another type of database service on the same prefix. If both do some service discovery via dns they might make the wrong assumption about the service they are connecting too (eg wrong vendor / product protocol).

But in our use case, there is no real conflict. We are not running a service on these dns names. It’s just the dns lookup itself that has the data.

On top of that, we encourage using known vendor name and service name so that in itself avoids conflicts. Registering these names is extra effort for companies that have no IANA relationship and it will also just pollute the underscore registry with a lot of vendor names. It might cause people to need to talk to lawyers about trademarks.

It might be good to advise the readers to check the underscore registry to avoid collisions, eg for a company that happens to be called dmarc so they can use “_dmarc-llc” or something. But I see no reason to register new entries. Eg what is the value for Aiven to add _aiven there ? The chance of another company called Aiven that also is in tech that also has services they want to validate via an _aiven prefix is about zero. And if it happens, it doesn’t actually matter if there would be two _aiven records at the customer where each one verifies one vendor/service.

Paul

**Comment by moonshiner** [comment]
So we can add some text in section 5.1.2 Scope Indication

"Application owners should consult the IANA Underscore registry (linky link) to confirm there are no collisions with existing entries. "

Also in 5.1.2 there is a dangling " (see #scope)"

**Comment by moonshiner** [comment]
https://github.com/ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques/pull/113
