### ISSUE TITLE
DNAME

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#26]
discuss

**Comment by shuque** [comment]
Some quick thoughts.

Since DNAME redirects the entire subtree of names underneath the owner of the DNAME, you cannot place an underscore name under the DNAME itself - it would have to be placed under the DNAME target name, since any lookups for an underscore at the DNAME will be redirected to the corresponding label under the DNAME target. This may be sufficient to verify ownership of both the DNAME source and/or target zone.

**Comment by moonshiner** [comment]
I would suggest if you want to mention DNAME, you'll want to include a working example.
