### ISSUE TITLE
Describe delegated domain control validation

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-dnsop/draft-ietf-dnsop-domain-verification-techniques#57]

**Comment by moonshiner** [comment]
This is from the cloudflare site

Delegated DCV

Delegated DCV allows SaaS providers to delegate the DCV process to Cloudflare.

DCV Delegation requires your customers to place a one-time record at their authoritative DNS that allows Cloudflare to auto-renew all future certificate orders, so that there is no manual intervention from you or your customers at the time of the renewal.

https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/security/certificate-management/issue-and-validate/validate-certificates/delegated-dcv/

**Comment by ShivanKaul** [comment]
I think I'll merge in the attached PR, there's quite a few piling up issues that it will fix and we can start making sense of the reworked doc then.
